### PR TITLE
CI Pipeline Initial Test (not fork)

### PR DESCRIPTION
**Pull request by kieron-dev**

### CODE REVIEW

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Review by avade — COMMENTED** [review]
Please remove the hello world message.

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kieron-dev** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by servicesenablement** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by servicesenablement** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Pull request closed without merging**
